version: "3.7"
services:
  backend:
    build: .
    container_name: backend-container
    environment:
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=secret_key
      - MONGODB_URI=mongodb+srv://sgsong:DladmlfhAksemsDmlaldjqtsmsQlalfqjsgh@chic-cluster.cnqva.mongodb.net/
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
      - .:/app
      - ./node_modules:/app/node_modules
    restart: always
